### ISSUE TITLE
responsive layout (routes missing)

### ISSUE THREAD

**Issue by the-vampiire** [chingu-x/chingu-client#22]
when the CDN is viewed on any viewport smaller than full desktop the routes disappear

they need to be in a hamburger or at least displayed across the top

**Comment by the-vampiire** [comment]
the Chingu korean symbol (im assuming) is a nice touch but may be confusing to people. what if we used that as our “hamburger” like icon for the mobile view of the routes? make it symbolic like an icon

**Comment by Oxyrus** [comment]
I haven't been able to figure out how to integrate the hamburger of MaterializeCSS with our React client, we will have to do it with pure CSS. The Korean word was just for me, I don't know if we should use the Chingu logo or just the word `Chingu`.
