### ISSUE TITLE
Apply button

### ISSUE THREAD

**Issue by the-vampiire** [chingu-x/chingu-client#23]
vampiire [2 hours ago] 
if apply is a dead link im wondering if we should remove it from the MVP

as i understand apply will be sending them to eddy’s project which isnt live right now (or is it - enough to add a link to?)

it is also confusing between apply / sign up (remember we need to think from the judge’s perspective who have no idea about our internal workings)

suggestion:
move signup to “apply” position temporarily for the purposes of the mvp

**Comment by Oxyrus** [comment]
I think apply will just point to sign up, and the later will be renamed to apply, so

`/apply` would be the current sign up thing.
